### ISSUE TITLE
Issue with pyopengl library

### ISSUE THREAD

**Issue by WisarutBholsithi** [TimoBolkart/TF_FLAME#10]
Dear developers,

I have installed all the library and python for using TF_Flame program.
However, when I tried to run the example by typing "**python sample_FLAME.py**", I got the following error instead:

**AttributeError: 'NoneType' object has no attribute 'glGetError'**

Something must have gone wrong with pyopengl library for TF_Flame.
Therefore, I would like to know which version of pyopengl library you are using for TF_Flame project so I deal with Attritbute Error problem.

![ErrorinPyOpenGLinTF_Flame](https://user-images.githubusercontent.com/58510558/70137681-1250b600-16c1-11ea-9dc9-fce1a8c3acf0.jpg)

**Comment by TimoBolkart** [comment]
We are using pyopengl version 3.1.0

**Comment by WisarutBholsithi** [comment]
Thanks for your advice. 
I have to make an additional note that I need to install  python-opengl (python openGL library ) by the following command:

apt-get install python-opengl

This one is to deal with the problem "**('GL: cannot open shared object file: No such file or directory', 'GL', None)**" which I have seen while running 

The only catch right now is to find the FLAME Tensorflow model files to fill in models directory though.
When I have been to the [Flame Page](http://flame.is.tue.mpg.de/), I still unable to find any link to download the flame models in the page in question.

I just wonder whether it is possible to create FLAME Tensorflow model files on our own though.

**Comment by TimoBolkart** [comment]
Thanks for the feedback.

> The only catch right now is to find the FLAME Tensorflow model files to fill in models directory though.
When I have been to the Flame Page, I still unable to find any link to download the flame models in the page in question.

You need to sign up and agree to the model license for access to the model and the data. Signing in enables a download tab where you find the download links.

> I just wonder whether it is possible to create FLAME Tensorflow model files on our own though.

FLAME is trained from more than 33,000 head scans of about 4000 subjects. Building a FLAME model your self requires not only all the processed data but also an involved model training pipeline. Please see the [paper](https://ps.is.tuebingen.mpg.de/uploads_file/attachment/attachment/400/paper.pdf) for details. Building a model yourself hence is then probably not an option.

**Comment by WisarutBholsithi** [comment]
How can I sign up the agreement for both Data License and Model License to be used in TF_Flame? I have been to the pages [[Data License](http://flame.is.tue.mpg.de/data_license)] and [[Model License](http://flame.is.tue.mpg.de/model_license)] so as to get permission to use Flame Data/Model.

**Comment by TimoBolkart** [comment]
On the FLAME website there is a "sign up" button at the top right. There you need to register in order to get access. Apologies for the inconvenience but since the model contains human subjects data, we are required to do this.

**Comment by WisarutBholsithi** [comment]
Now, I just sign up and modified some codes to make it compatible with future version of TensorFlow as follows:


```
def sample_FLAME(template_fname, tf_model_fname, num_samples):
 ...
    saver = tf.compat.v1.train.import_meta_graph(tf_model_fname + '.meta')
    graph = tf.compat.v1.get_default_graph()
    # saver = tf.train.import_meta_graph(tf_model_fname + '.meta')
    # graph = tf.get_default_graph()
```
....
```
    # with tf.Session() as session:
    with tf.compat.v1.Session() as session:
        saver.restore(session, tf_model_fname)

        # Workaround as existing tf.Variable cannot be retrieved back with tf.get_variable
        tf_trans = [x for x in tf.compat.v1.trainable_variables() if 'trans' in x.name][0]
        tf_rot = [x for x in tf.compat.v1.trainable_variables() if 'rot' in x.name][0]
        tf_pose = [x for x in tf.compat.v1.trainable_variables() if 'pose' in x.name][0]
        tf_shape = [x for x in tf.compat.v1.trainable_variables() if 'shape' in x.name][0]
        tf_exp = [x for x in tf.compat.v1.trainable_variables() if 'exp' in x.name][0]
        # tf_trans = [x for x in tf.trainable_variables() if 'trans' in x.name][0]
        # tf_rot = [x for x in tf.trainable_variables() if 'rot' in x.name][0]
        # tf_pose = [x for x in tf.trainable_variables() if 'pose' in x.name][0]
        # tf_shape = [x for x in tf.trainable_variables() if 'shape' in x.name][0]
        # tf_exp = [x for x in tf.trainable_variables() if 'exp' in x.name][0]
```
....
```
        for i in range(num_samples):
            assign_trans = tf.compat.v1.assign(tf_trans, np.random.randn(3))
            assign_rot = tf.compat.v1.assign(tf_rot, np.random.randn(3) * 0.03)
            assign_pose = tf.compat.v1.assign(tf_pose, np.random.randn(12) * 0.03)
            assign_shape = tf.compat.v1.assign(tf_shape, np.random.randn(300) * 1.0)
            assign_exp = tf.compat.v1.assign(tf_exp, np.random.randn(100) * 0.5)
            # assign_trans = tf.assign(tf_trans, np.random.randn(3))
            # assign_rot = tf.assign(tf_rot, np.random.randn(3) * 0.03)
            # assign_pose = tf.assign(tf_pose, np.random.randn(12) * 0.03)
            # assign_shape = tf.assign(tf_shape, np.random.randn(300) * 1.0)
            # assign_exp = tf.assign(tf_exp, np.random.randn(100) * 0.5)
```
...
```
def draw_random_samples():
    # Path of the Tensorflow FLAME model
    tf_model_fname = './models/tf_models/generic_model' #  
    # tf_model_fname = './models/female_model'
    # tf_model_fname = './models/male_model'
    # tf_model_fname = './models/generic_model' # this has gone missing!
```

....

```
def draw_VOCA_template_sample():
    # Path of the Tensorflow FLAME model
    # tf_model_fname = './models/generic_model'
    # tf_model_fname = './models/female_model'
    tf_model_fname = './models/tf_models/male_model'
    # tf_model_fname = './models/male_model'
```
However, I got the following error before getting error on OpenGL

> 2019-12-11 10:03:51.821069: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
> 2019-12-11 10:03:51.826706: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 2809310000 Hz
> 2019-12-11 10:03:51.826877: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x559cf6112ae0 executing computations on platform Host. Devices:
> 2019-12-11 10:03:51.826941: I tensorflow/compiler/xla/service/service.cc:175]   StreamExecutor device (0): <undefined>, <undefined>

Here is the error related to OpenGL:

> Use standard file APIs to check for files with this prefix.
> 2019-12-11 10:03:51.849911: W tensorflow/compiler/jit/mark_for_compilation_pass.cc:1412] (One-time warning): Not using XLA:CPU for cluster because envvar TF_XLA_FLAGS=--tf_xla_cpu_global_jit was not set.  If you want XLA:CPU, either set that envvar, or use experimental_jit_scope to enable XLA:CPU.  To confirm that XLA is active, pass --vmodule=xla_compilation_cache=1 (as a proper command-line flag, not via TF_XLA_FLAGS) or set the envvar XLA_FLAGS=--xla_hlo_profile.
> 2019-12-11 10:03:51.886458: W tensorflow/core/framework/allocator.cc:107] Allocation of 48220800 exceeds 10% of system memory.
> OpenGL test failed:
>         stdout:
>         stderr: freeglut  (foo) : failed to open display ''   Press key to continue     

![ErrorofTryingtoOpen3DHeadImageBeforeSettingTF_CPP_MIN_LOG_LEVELto3](https://user-images.githubusercontent.com/58510558/70612456-85b27480-1c39-11ea-87a7-7441b46cf510.jpg)

How can I deal with this kind of trouble? 
Even After I have set TF_CPP_MIN_LOG_LEVEL to 3 as the way to suppress the warning related to CPU and Memory, the OpenGL error related to glut still persists
![ErrorofTryingtoOpen3DHeadImageAfterSettingTF_CPP_MIN_LOG_LEVELto3](https://user-images.githubusercontent.com/58510558/70612495-94992700-1c39-11ea-8ee3-a3f81a6efaa6.jpg)

I run TF_Flame program through Docker and the PC (Laptop to be more exact) is Windows10  64-bit with 16 GB of RAM  with Intel CPU of Core i-7 at 2.80 GHz.

![Windows10ofMyLaptop](https://user-images.githubusercontent.com/58510558/70612845-446e9480-1c3a-11ea-809e-334bb07c4680.jpg)

Hope that there will be a solution for such problem.

**Comment by jjandnn** [comment]
@WisarutBholsithi 
!pip install pyvirtualdisplay

# 启动虚拟显示器
from pyvirtualdisplay import Display
display = Display(visible=0, size=(1400, 900))
display.start()

**Comment by TimoBolkart** [comment]
@WisarutBholsithi the demo uses an OpenGL-based viewer to visualize the samples, however that is not essential for sampling the model as you can check the meshes also after writing them to disk. As a workaround, please pull the newest version of the code and run the demo with a flag --visualize False, this will disable the visualization.
