### ISSUE TITLE
tf_models vs texture_data.npy

### ISSUE THREAD

**Issue by scott-vsi** [TimoBolkart/TF_FLAME#13]
I was exploring fit_2D_landmarks.py and noticed that the result_mesh returned by `fit_lmk2d` on line [171](https://github.com/TimoBolkart/TF_FLAME/blob/a2937baa07f0c34395f68f4dac4987f8174e8ee0/fit_2D_landmarks.py#L171) has 5023 vertices (`len(result_mesh.v) == 5023`), as does the tf_model loaded by `fit_lmk2d` from the models/generic_model.meta file.

However, the texture coordinates loaded from data/texture_data.npy file, which you use to set `result_mesh.vt` on line [184](https://github.com/TimoBolkart/TF_FLAME/blob/a2937baa07f0c34395f68f4dac4987f8174e8ee0/fit_2D_landmarks.py#L184), has length 5118 (`len(texture_data['vt']) == 5118`).

Shouldn't these two arrays have the same length?

**Comment by TimoBolkart** [comment]
Can you please specify if there is any problem when running the texture demo?
The number of vertices and the number of texture coordinates do not need to be equal as some vertices map to multiple texture coordinates along added texture boundaries (i.e. seams that got added to split the texture map like done at the back of the head). Does that answer your question?
Running the demo will give you an idea how the texture map looks.

**Comment by scott-vsi** [comment]
I see. Thanks for the explanation
