### ISSUE TITLE
Ladmarks used in fit_2D_landmarks.py

### ISSUE THREAD

**Issue by mrgloom** [TimoBolkart/TF_FLAME#14]
<img width="1169" alt="example_2" src="https://user-images.githubusercontent.com/4003908/74199196-90f34200-4c74-11ea-9407-fc84e26d868e.png">
I wonder why only subset of landmarks is used? i.e. why jaw landmarks is not used? seems person identity can be better preserved with more landmarks?

**Comment by TimoBolkart** [comment]
You are certainly right, using the contour landmarks additionally will help you to get a better shape. The problem is that the contour landmarks do not have a fixed embedding in the 3D mesh but depend on the rotation angle. We will adapt this in the near future to consider all keypoints.

**Comment by Vozf** [comment]
What exact landmarks are you using? 
https://github.com/1adrianb/face-alignment outputs 68 landmarks while you are using only 51. How to choose this 51 landmarks out of 68?

**Comment by mrgloom** [comment]
51 landmarks is actually subset of 68 i-bug landmarks / dlib landmarks, face-alignment seems have the same set of landmarks.

You can get 51 point subset like(not tested):
landmarks = landmarks_68[16+1:]
landmarks = landmarks[:51]


You can draw provided example data to check idx of landmarks like:

```
import os
import argparse

import cv2
import numpy as np


def draw_landmarks(img_path, lms_path):
    img = cv2.imread(img_path)
    lms = np.load(lms_path)

    for i in range(lms.shape[0]):
        x = int(lms[i][0])
        y = int(lms[i][1])
        cv2.circle(img, (x, y), radius=1, color=(0,0,255), thickness=1)
        cv2.putText(img, str(i), (x, y), cv2.FONT_HERSHEY_SIMPLEX, 0.5, 255, thickness=1)

    out_path = os.path.splitext(img_path)[0] + '_lms.png'
    cv2.imwrite(out_path, img)


if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument('img_path')
    parser.add_argument('lms_path')
    args = parser.parse_args()

    draw_landmarks(args.img_path, args.lms_path)
```

**Comment by emlcpfx** [comment]
> You are certainly right, using the contour landmarks additionally will help you to get a better shape. The problem is that the contour landmarks do not have a fixed embedding in the 3D mesh but depend on the rotation angle. We will adapt this in the near future to consider all keypoints.

Any chance you have the code for this?
