### ISSUE TITLE
How to set parameters to find some concrete expressions? 

### ISSUE THREAD

**Issue by plmsmile** [TimoBolkart/TF_FLAME#16]
Thanks for share of the great work!!! Recent days I am working on FLAME and VOCA.

I met a problem: I want to set some concrete expressions(eg. smile or cry or laugh ...) to a specific model, however I don't know what the expression parameters to set(eg. 0.1 or 0.2 or 0.3). 

Can you give me some advice for parameter values to concrete shape/pose/expressions? Thank you very much.

**Comment by TimoBolkart** [comment]
FLAME models facial expressions (i.e. without the jaw pose to open the mouth) with a linear expression space computed by PCA. The different components hence have no semantic meaning. You could use this [web demo](https://tpsmpi.github.io/flameweb/) however to play with the expression components of the FLAME2020 models.
