### ISSUE TITLE
Question about Face Contour and Head shape from 2D Landmarks

### ISSUE THREAD

**Issue by Lord-Ashura** [TimoBolkart/TF_FLAME#18]
Thank you for your fantastic work, but I had a question related to how FLAME generates the proper Head Shape and Face Contour from 2D Landmarks.

From what I have seen, you use the 49 Landmarks on the Facial Features to generate the Head Model.

How is the contour of the face and head determined if you do not use the contour landmarks to help generate the head shape? 

Thank you and I hope to hear from you soon!

**Comment by TimoBolkart** [comment]
You are right, in the 2D landmark fitting demo that we provide here, we only use the static 49 face inside landmarks and fit FLAME to these landmarks. By ignoring the face contour landmarks, the face shape you get by this demo is not optimal. We ignore the contour landmarks as they don't have a fixed embedding but move on a trajectory in the face depending on the rotation angle of the face.
However, you can find a dynamic landmark embedding of the contour landmarks into the FLAME face geometry [here](https://github.com/soubhiksanyal/RingNet) which could be used to improve the fitting quality.
