### ISSUE TITLE
The "tf_pose" of the updated code seems to be invalid

### ISSUE THREAD

**Issue by fastcode3d** [TimoBolkart/TF_FLAME#20]
When removing the expression parameters and using the old version of code to fit the mouth opening model, the result model is correct. But when I use the new version of model to fit, the fitting result model is not mouth opening. (the jaw parameter will lead to mouth opening). tf_pose parameter seems to be not quite right. Do anyone know the reason?

**Comment by TimoBolkart** [comment]
Can you give few more details? What are you trying to do? Fit FLAME to an image? 

And with the current code there are differences between FLAME2019 and FLAME2020? Is that what you mean?

**Comment by TimoBolkart** [comment]
Can you also show some images to demonstrate what you mean?

**Comment by fastcode3d** [comment]
Yes, I try to fit the FLAME to the picture with the new code. But the result is not consistent with the old version of the flame. It seems that the "TF pose" parameter in the new code is invalid
This is the effect of current code fitting:
![2020-04-29 11-46-03 的屏幕截图](https://user-images.githubusercontent.com/42864265/80559421-08cd3f00-8a10-11ea-8373-7c8655ea1f26.png)

This is to remove the effect of expression parameter fitting:
![Uploading 2020-04-29 11-44-21 的屏幕截图.png…]()

The "TF pose" parameter should be able to control jaw opening and closing, but it seems to fail

**Comment by TimoBolkart** [comment]
One thing that could cause this in this example is the contour. It seems the contour in your example is already well fit, and opening the mouth with the jaw parameters would add an error to almost all of the contour keypoints in the lower half of the face. Could you run the same fitting example but without contour landmarks, to see if jaw pose captures the mouth opening then?

I did some experiments to see if the tf_pose is working and it 1) the model has a gradient w.r.t. tf_pose, and 2) I did a dummy fitting example, where I manually opened the mouth by activating the jaw rotation, projected the model landmarks to the image, and only fitted these. For this, the jaw pose did get optimized and the mouth opening got fitted. So in principle it should work.

**Comment by fastcode3d** [comment]
Thank you very much for your reply.
This is the convergence result of current code fitting(51 lmk):
![2020-05-06 10-18-28 的屏幕截图](https://user-images.githubusercontent.com/42864265/81133240-96b2a800-8f83-11ea-9d4e-c606f5a7fd28.png)

This is the convergence result without expression parameter  of current code fitting
![2020-05-06 10-20-03 的屏幕截图](https://user-images.githubusercontent.com/42864265/81133248-9ca88900-8f83-11ea-896b-d9ff2bf65e2e.png)

ori image:
![000](https://user-images.githubusercontent.com/42864265/81133301-c661b000-8f83-11ea-8760-c453049ded92.jpg)

**Comment by fastcode3d** [comment]
In older versions of code, the fit worked：
![2020-05-06 10-27-27 的屏幕截图](https://user-images.githubusercontent.com/42864265/81135376-85b96500-8f8a-11ea-966d-9472cc5a998d.png)

**Comment by TimoBolkart** [comment]
Indeed, you are right. The problem is fixed now. 

In contrast to the old model, the newly integrated model loading has the batch size as the first dimension, which is 1 for the fitting example. The pose priors however did not consider this properly, which caused an unexpected behavior when optimizing for pose. Can you please pull the new changes and confirm that it is working for you? Thanks again for pointing this out.

**Comment by fastcode3d** [comment]
I tested the latest version, no problem.
Thank you very much.
