### ISSUE TITLE
Fit 3D landmarks example

### ISSUE THREAD

**Issue by fogside** [TimoBolkart/TF_FLAME#22]
I tried to run demo with 3d fitting and I got some strange result.
I supposed to get mesh looking similar to the `./data/registered_mesh.ply` but I got smth very different. But landmarks look like a good fit.
Probably I do smth wrong. But I didn't change the original script.

Here on the right is the result I got, on the left -- registered_mesh.ply.
![Screenshot from 2020-05-04 19-32-13](https://user-images.githubusercontent.com/6944359/80991362-93fb6a00-8e40-11ea-8d2a-1925b343af83.png)

**Comment by TimoBolkart** [comment]
The landmarks on the left are the ones you used for fitting? Why do you expect an output like seen on the right? While the right mesh has a smile expression, the landmarks on the left seem not very expressive. Can you please clarify what and why you expected this? Maybe I misunderstand something
