### ISSUE TITLE
Fit FLAME to a 3D mesh

### ISSUE THREAD

**Issue by nikanfds** [TimoBolkart/TF_FLAME#23]
Hi, it's literally an impressive work!

I want to know of the possibility to fit FLAME to 3D mesh which doesn't have topology of the FLAME and it just covers the frontal part of the face (it's a face point cloud after triangulation).

Thanks.

**Comment by TimoBolkart** [comment]
Thank you, please check out the FLAME paper on how to align a general scan that is not in FLAME topology. The basic idea would be to replace the vertex to vertex distance from the fit_3D_mesh demo with a general point to surface distance and minimize this instead.

**Comment by TimoBolkart** [comment]
We just added some demo code to fit FLAME to as can of arbitrary topology in the [flame-fitting repo](https://github.com/Rubikplayer/flame-fitting).
