### ISSUE TITLE
a question about valid_pixel_ids

### ISSUE THREAD

**Issue by alicedingyueming** [TimoBolkart/TF_FLAME#25]
Dear author,
thanks for the great work! I am sorry to bother you, I have a question about the selection of valid_pixel_ids. I see that the  valid_pixel_ids is about the valid pairs of x_coords and y_coords. how do you generate the valid_pixel_ids？ do you have any reference？

**Comment by alicedingyueming** [comment]
well it seems that the valid_pixel_ids are pixels enveloped in the valid_pixel_3d_faces

**Comment by TimoBolkart** [comment]
The valid_pixel_ids are basically all pixels of the image that are within a UV triangle of the FLAME mesh. Note that we created multiple FLAME_texture_data files for different texture resolutions (i.e. 256x256, 512x512, 1024x1024, 2048x2048) which you can download from [here](http://files.is.tue.mpg.de/tbolkart/FLAME/FLAME_texture_data.zip). See the updated code of the repo how to handle these.

**Comment by Monibsediqi** [comment]
Hi, I've been looking for texture_space models of size 256x256, 512x512 and 1024x1024 but can't find them. The link that you've shared is also not accessable anymore. How can find those textures?

**Comment by TimoBolkart** [comment]
Can you please specify which link is not accessible anymore? The texture space models are available under the same download link than the FLAME model ([download](https://flame.is.tue.mpg.de/download.php)) after signing up and agreeing to the license. Does that work for you?

**Comment by Monibsediqi** [comment]
Thank you for the prompt reply. Looks like the problem was with my browser (chrome) that I couldn't access the link in the above previous comment. I switched to another browser and could download the files. Thanks 👍
