### ISSUE TITLE
About build_texture_from_image.py

### ISSUE THREAD

**Issue by Ten1o** [TimoBolkart/TF_FLAME#26]
Hi, Thanks for your excellent work!

I've been trying to figure out how to use an image to build texture to the FLAME mesh (using build_texture_from_image.py) and I had several questions:

1. I saw the file needs to take in a pre-computed parameter "target_scale". I'm wondering how to calculate this parameter if I want to align my own image with its FLAME mesh.

2. I noticed that the example meshes given (such as imgHQ00039.obj) are not zero-centered. They have offsets from the origin and it seems that this offset is useful for calculating the texture map. How is this offset chosen?

Thanks for answering!

**Comment by TimoBolkart** [comment]
Hi,

The association of FLAME with those images is established in the fit_2D_landmarks.py.
Both, the model translation and the scale are parameters that are optimized within the fit_lmk2d function by minimizing the reprojection loss between the (projected) model landmarks and the predicted image landmarks.
Does this answer your question?

**Comment by Ten1o** [comment]
Yes! Thanks for your answer. I will check that file!

**Comment by zhangqijun** [comment]
I'm sorry ,where is imgHQ00088.obj

**Comment by Ten1o** [comment]
> I'm sorry ,where is imgHQ00088.obj

I'm not sure but you can check https://github.com/TimoBolkart/TF_FLAME#fit-2d-landmarks , which may be used to generate the obj file.
