### ISSUE TITLE
Arbitrary 3D face fitting

### ISSUE THREAD

**Issue by YihuanL** [TimoBolkart/TF_FLAME#3]
Hello, I found the result is great and I wonder to know is there any suggestion for Arbitrary 3D face fitting? Thanks in advance.

**Comment by TimoBolkart** [comment]
Can you please elaborate more on what you mean with "Arbitrary 3D face fitting"? Fitting an arbitrary model? Fitting to arbitrary data?

**Comment by YihuanL** [comment]
Sorry for that misunderstanding, yes, I mean fitting to arbitrary data.

**Comment by TimoBolkart** [comment]
The optimization would be similar than for the fitting to 3D landmarks but it would require optimizing a different objective function. E.g. for fitting to 2D landmarks, one would need to optimize the difference between the 3D landmarks projected to 2D, and predicted 2D landmarks, or for fitting a 3D scan, one would need to optimize a scan-to-mesh or a mesh-to-scan distance.

**Comment by YihuanL** [comment]
Got it, Thanks.

**Comment by GucciPrada** [comment]
I'm also interested in this topic,  although it was closed, may I ask a question here: 
Whether the code in fit_3D_mesh.py can be modified to register the FLAME model or template mesh to an arbitrary 3D face scan(e.g. the scan has different topology)?
