### ISSUE TITLE
Adding More Landmarks

### ISSUE THREAD

**Issue by alexrichardson21** [TimoBolkart/TF_FLAME#30]
I've noticed the neck tends to be a little off because the flame landmark embedding is missing any sort of neck landmark. If I wanted to add to the embedding using some openpose landmarks, how would i find the barycentric coordinates for the new landmarks?

**Comment by alexrichardson21** [comment]
Or is there a way to build a more cohesive temporal fitting process instead of just the single frame?

**Comment by TimoBolkart** [comment]
Another option could be not only optimizing a landmark loss but additionally optimizing some photometric loss (see e.g. [this demo](https://github.com/HavenFeng/photometric_optimization) for details how to do this). This provides more supervision than keypoints only. 
And yes, certainly one could do a joint optimization with some temporal regularization to multiple consecutive frames of a video.

**Comment by alexrichardson21** [comment]
Interesting. I was using SMPLify X before but it runs significantly slower than FLAME fitting. Haven't looked into photometric loss yet so that seems worth a try

**Comment by hbinol** [comment]
> Interesting. I was using SMPLify X before but it runs significantly slower than FLAME fitting. Haven't looked into photometric loss yet so that seems worth a try

Hi Alex!

I wonder if you had a chance to look at any neck landmarks/positions?
