### ISSUE TITLE
The number of uv coordinates is not equal to the number of vertices.

### ISSUE THREAD

**Issue by enjoybo** [TimoBolkart/TF_FLAME#33]
Hi, thanks for your great project. I found that the number of uv coordinates is 5118 but the number of vertices of Flame is 5023. Did I miss something? How to get the colors of every vertex?

**Comment by viliusmat** [comment]
I have not looked at the models uv map, but it might be the case that models texture map has texture seems (to minimize the uv streching). In this case some of the 3d vertices might have 2 different uv coordinates. Like in image the marked vertices in uv space are actually a single vertex in 3d space.

![pr_head_wip_zbrush_uv](https://user-images.githubusercontent.com/45842036/94541909-d474dd80-0250-11eb-9283-e008ce8cd5f6.jpg)

**Comment by TimoBolkart** [comment]
That is right, the uv faces and the 3D faces are corresponding but the 3D vertices and texture coordinates are not. One 3D vertex corresponds to multiple uv coordinates if it is on a boundary as pointed out by @viliusmat

**Comment by enjoybo** [comment]
Got it. Thanks.

**Comment by ra1995** [comment]
@enjoybo Hi, I might have missed it in the repo, but I really need these raw uv coordinates, how can I get a list of these aligned uv coordinates. Please help me out, I tried mesh unwrap in blender to make my own uv map but its really bad. Thanks in advance.

**Comment by TimoBolkart** [comment]
The texture coordinates are part of the [FLAME_texture_data](http://files.is.tue.mpg.de/tbolkart/FLAME/FLAME_texture_data.zip). You can also just run any of the provided demos like fit_2D_landmarks.py or sample_texture.py which will output a mesh with the texture coordinates.

**Comment by ra1995** [comment]
Thanks
