### ISSUE TITLE
about dynamic_lmk_faces_idx

### ISSUE THREAD

**Issue by alicedingyueming** [TimoBolkart/TF_FLAME#35]
Sorry for bothering you. Thanks for your great work! I am trying the texture model of TF-FLAME now, and I notice that there is a dynamic_lmk_faces_idx data. could you give me some hints to understand that?

**Comment by TimoBolkart** [comment]
Can you please specify your question? What do you want to do? What are you trying out? And how is the dynamic_lmk_faces_idx related to the texture model?
