### ISSUE TITLE
Any pre-scanned full textures available?

### ISSUE THREAD

**Issue by kyungjin-lee** [TimoBolkart/TF_FLAME#36]
Hello, thank you so so much for this amazing work! I'm really enjoying playing around with it.
I have tried the fit_2D_landmark demo and since the texture cannot be generated for occluded regions in the 2D image (i.e. ears) I was wondering if there is a pre-scanned complete texture for any subject so that I can use it as a base texture and just update the valid parts with my own image. 
Or if you can recommend some other way, that'd be great.

Also, is it possible to use a single pre-scanned texture template for all the fitted meshes? (might be a very trivial question, I'm very new to computer graphics :'))
Thank you so much again!

**Comment by TimoBolkart** [comment]
There are different possibilities to get complete textures. One option is to get a complete texture from a scan, e.g. the [Headspace dataset](https://www-users.cs.york.ac.uk/~nep/research/Headspace/ ) provides registered FLAME meshes for 1216 scans where one could project the original camera images onto to get a complete texture. One option is to use the provided texture space to get a complete texture (but more blurry than a real texture). Another option is to take the incomplete texture and run some texture completion method on. One could also do some fusion, e.g. by fitting FLAME with texture space to an image (e.g. using [this FLAME fitting repo](https://github.com/HavenFeng/photometric_optimization)) and fuse the obtained model texture with the projected image. I guess it depends on your use case. Does this answer your question?

**Comment by kyungjin-lee** [comment]
Yes very clear now. Thank you so much!

**Comment by RAJA-PARIKSHAT** [comment]
@kyungjin-lee Did you figure out how to do that? If yes, can you describe it in a bit of detail, that would be appreciated...
