### ISSUE TITLE
About flame_model.J_regressor,  flame_model.kintree_table and flame_model.weights

### ISSUE THREAD

**Issue by enjoybo** [TimoBolkart/TF_FLAME#38]
Thanks for your great work. I want to change the FLAME model to other 3DMM model, like BFM09, but I can't find the keys these three keys in BFM09 model. Could you please describe how to generate these three keys? Thanks.

**Comment by TimoBolkart** [comment]
May I ask why you want to replace FLAME by BFM? As shown in the [paper](https://ps.is.tuebingen.mpg.de/uploads_file/attachment/attachment/400/paper.pdf) in Section 7.3, FLAME is more expressive than BFM or FaceWarehouse model. Replacing FLAME with BFM will lead to worse performance.

**Comment by enjoybo** [comment]
Thanks for the quick reply. Now I'm studying 3D face reconstruction based on FLAME, but my reconstruction result is worse than the open source project: https://github.com/sicxu/Deep3dPortrait. So I want to replace FLAME by BFM to verify whether I made some mistake.

**Comment by TimoBolkart** [comment]
Since BFM is not our model, we cannot provide something for it. But if you tell us what you did and how your results look, we maybe can support you to get better results with FLAME. We could do this also through email rather than here.

**Comment by enjoybo** [comment]
That will be great, I will email you the results I got later. Thank you so much.

**Comment by enjoybo** [comment]
Hello Dr. Bolkart, it seems that my email has been blocked by the firewall. May I confirm that whether you can receive my email sent by liangborong@stu.xmu.edu.cn?

**Comment by TimoBolkart** [comment]
@enjoybo yes, I received your email and I will answer it soon
