### ISSUE TITLE
Is it possible to register the FLAME model to an arbitrary 3D face scan of different topology?

### ISSUE THREAD

**Issue by GucciPrada** [TimoBolkart/TF_FLAME#4]
Thanks for this project, it's the first full-head Morphable Model as far as I know!

Whether the code in fit_3D_mesh.py can be modified to register the FLAME model or template mesh to an arbitrary 3D face scan(e.g. the scan has different topology)?

**Comment by TimoBolkart** [comment]
Yes, this is indeed possible. You need a differentiable distance of a scan and the model's surface (e.g. a scan-to-mesh or a mesh-to-scan distance). Then you only would need replace the used distance function to the 3D landmarks by this new distance to the scan surface.

**Comment by GucciPrada** [comment]
Thanks for your reply! I'll look into it

**Comment by samuelsunarjo96** [comment]
@GucciPrada were you able to figure a way to register arbitrary scan?
