### ISSUE TITLE
The shape parameters to change the width of neck independently

### ISSUE THREAD

**Issue by enjoybo** [TimoBolkart/TF_FLAME#40]
Hello Dr. Bolkart, I trained a deep network to predict the parameters of face reconstruction with Flame. Now the shape of face looks good but the width of neck looks larger than the input image. I expanded the mask to cover the neck when computing the photometric loss but the result looks almost the same. Is there any parameter of shape could change the width of neck and won't change the shape of face?

**Comment by TimoBolkart** [comment]
Hi, that sounds like a good progress. In general, the shape of the neck is correlated to the face shape, so optimizing for the face shape will affect the neck shape. There is not really a parameter that controls only the neck shape, but if you want a more thin neck, you could add some loss during training that penalizes the width of the neck (i.e. select some vertices on left and right side of the neck and just minimize the distance between them). However I have never experimented with this and this might influence the face shape reconstruction negatively, so I advice carefully weighting this term. Does that help?

**Comment by enjoybo** [comment]
Yes, the advice you provided helps a lot. Now most of the reconstruction results look good but still have bad cases. I'm still working on improving the performance and stability. The width of neck is too large so that the result looks a little dissonant. I'm trying to add some constraints to keep the neck thinner.

**Comment by enjoybo** [comment]
Hello Dr. Bolkart, Thanks for your great advice again. In the Interactive Model Viewer onthe website: https://flame.is.tue.mpg.de/interactive-model-viewer, there are pose articulations of head and jaw. Are these two articulations included in the shape and expression parameters? If yes, which shape and expression parameters could control the pose articulations of head and jaw?

**Comment by TimoBolkart** [comment]
Sorry for the late reply. The pose parameters are a separate set of parameters represented as axis-angle rotations. The pose parameters of FLAME consist of 15 parameters, i.e. 3 for global rotation, 3 for head rotation around the neck, 3 for jaw rotation, and 3 parameters for each of the eyeballs.
