### ISSUE TITLE
Fit to animation

### ISSUE THREAD

**Issue by 5agado** [TimoBolkart/TF_FLAME#42]
Awesome project! I'm playing around with it together with the Blender add-on.

I was curious about the possibility of fitting animated FLAME models, being it from 2D landmarks or even from videos.
In the video you showed captured performance from scan, but I believe that you didn't provide the code for that.
Also processing each frame (or landmarks) separately to generate a fit FLAME model doesn't sound optimal.

I tried for example [3DDFA_V2](https://github.com/cleardusk/3DDFA_V2) to get animated 3D mesh from video, but I don't have any idea how to transfer such information to a FLAME model.

Any input on this side is more that welcome, I will then also try the path of animation via VOCA

**Comment by TimoBolkart** [comment]
> I was curious about the possibility of fitting animated FLAME models, being it from 2D landmarks or even from videos.
> In the video you showed captured performance from scan, but I believe that you didn't provide the code for that.

You are right, so far we don't have that code available. But we plan to actually release some code soon to fit FLAME to a scan. 

> Also processing each frame (or landmarks) separately to generate a fit FLAME model doesn't sound optimal.

Indeed, fitting each frame separately is not optimal. Instead one could fit for each frame independently and then optimize some joint loss across multiple frames along with some temporal consistency term. This would make the result temporally coherent.

> I tried for example 3DDFA_V2 to get animated 3D mesh from video, but I don't have any idea how to transfer such information to a FLAME model.

I have seen 3DDFA_V2 but never played with it. We have some code available to convert a Basel Face Model mesh to FLAME [here](https://github.com/TimoBolkart/BFM_to_FLAME). I am not sure which subset of BFM vertices 3DDFA_V2 uses, so I am not fully sure if our converter script is compatible with it right now.

> Any input on this side is more that welcome, I will then also try the path of animation via VOCA

VOCA is certainly another option to get some FLAME animated mesh from speech only.

**Comment by 5agado** [comment]
Thank you @TimoBolkart for the detailed answer.
Looking forward with excitement to any additional code or research results. In the meantime I will try what you suggested and play around more with this and related projects.

Feel free to close the issue

**Comment by TimoBolkart** [comment]
Thank you for the feedback

**Comment by xiapengchng** [comment]
> I tried for example [3DDFA_V2](https://github.com/cleardusk/3DDFA_V2) to get animated 3D mesh from video, but I don't have any idea how to transfer such information to a FLAME model.

Did you transfer the BFM model without neck to the FLAME model? And How? Thanks a lot!
