### ISSUE TITLE
reconstruct 3d face with new expressions

### ISSUE THREAD

**Issue by genesis02** [TimoBolkart/TF_FLAME#43]
How to reconstruct 3d model if we have new expressions.

**Comment by TimoBolkart** [comment]
Can you please clarify your question more? What do you want to reconstruct a 3D model (or 3D mesh) from? Also, in which form is the expression provided?

**Comment by genesis02** [comment]
I have expression coefficients generated from some network based on input audio. And i also have 3d face constructed from a image using your model that has all coefficients shape, pose ,expressions etc.  Now i want to animate the expressions generated by the network on  the given 3d face like transferring the expressions. How to do it properly. Should i just replace these older coefficients with the new one or do something else.  Number of coefficients are same in both expressions.  And also how to render the uv maps from the newly constructed 3d face model. Please provide directions.  Thanks

**Comment by TimoBolkart** [comment]
How do you obtain the parameters given an audio sequence? Does this network output FLAME parameters? If yes, to transfer the expressions you only need to take the jaw pose AND expression parameters from the expression source sequence and combine it with the identity parameters of the identity source reconstruction.
