### ISSUE TITLE
Missing texture data

### ISSUE THREAD

**Issue by wbensvage** [TimoBolkart/TF_FLAME#46]
Thank you for the amazing work.
Just have one question. It seems there isn't texture_data_number.npy. And the download link seems invalid now?

**Comment by TimoBolkart** [comment]
Can you please point me to where texture_data_number.npy is being used? I am aware of the texture_data.npy, which can be downloaded  from here: [FLAME_texture_data](http://files.is.tue.mpg.de/tbolkart/FLAME/FLAME_texture_data.zip). This is the same link as provided in the readme and it works.
