### ISSUE TITLE
How is flame_static_embedding.pkl and flame_static_embedding_68.pkl created?

### ISSUE THREAD

**Issue by Anyman552** [TimoBolkart/TF_FLAME#48]
Hi there,

I am trying to understand how  the static embeddings are created. The pickle file contains ids and coordinates of the landmarks. From which obj. are those created? I want to add new landmarks and don't know which .obj-file to use for this.

**Comment by TimoBolkart** [comment]
Hi, the landmark files contain the triangle indices and the barycentric coordinates within that triangle for each landmark. As all meshes in FLAME topology are in dense vertex correspondence, you can select the landmark in any of the meshes. We usually do it in a neutral expression template like [that one](https://github.com/TimoBolkart/TF_FLAME/blob/master/data/template.ply).

**Comment by Anyman552** [comment]
Thank you very much.
