### ISSUE TITLE
how to normalize lmks3d?

### ISSUE THREAD

**Issue by ZHANG-SHI-CHANG** [TimoBolkart/TF_FLAME#6]
good job for me!
i want to know how to normalize the input lmks3d.The provided lmk3d is work well, like follow
![image](https://user-images.githubusercontent.com/30692249/64231222-8ee8c280-cf21-11e9-97f6-3593b3a81fc9.png)
but when i use lmk3d * 100, the result is bad.
![image](https://user-images.githubusercontent.com/30692249/64231497-644b3980-cf22-11e9-99f7-5d7f07713bd4.png)

**Comment by TimoBolkart** [comment]
As you see in the code, the 3D landmark fitting only optimizes for model parameters and not for a scale. As the model is is in units meter, the landmarks also have to be in the same units. Does this answer your question?

**Comment by ZHANG-SHI-CHANG** [comment]
> As you see in the code, the 3D landmark fitting only optimizes for model parameters and not for a scale. As the model is is in units meter, the landmarks also have to be in the same units. Does this answer your question?

i get it, thx~ very much.

**Comment by ZHANG-SHI-CHANG** [comment]
> As you see in the code, the 3D landmark fitting only optimizes for model parameters and not for a scale. As the model is is in units meter, the landmarks also have to be in the same units. Does this answer your question?

by the way, how to optimizes a scale?

**Comment by TimoBolkart** [comment]
You could add a global scale variable that isotropically scales the entire mesh and optimize these scale parameter jointly with all other parameters. Please be aware that knowing the true scale is beneficial compared to optimizing for an additional parameter

**Comment by ZHANG-SHI-CHANG** [comment]
> You could add a global scale variable that isotropically scales the entire mesh and optimize these scale parameter jointly with all other parameters. Please be aware that knowing the true scale is beneficial compared to optimizing for an additional parameter

get it, thx~ very much, i close it.
