### ISSUE TITLE
how to get variance of every shape and expression?

### ISSUE THREAD

**Issue by ZHANG-SHI-CHANG** [TimoBolkart/TF_FLAME#7]
hello, i want to know how to get variance of every shape and expression from flame model,i din't find it.

**Comment by TimoBolkart** [comment]
The shape and expression basis are multiplied by the standard deviation. This allows using a l2 norm as shape or expression prior (which is then equivalent to using Mahalanobis distance on the unit-length components). Varying a shape or oxpression component between +-x corresponds then to a variation of +-x standard deviations. 

If you reshape the shapedirs tensor from (num_verts x 3 x num_betas) to (3*num_verts * num_betas), the norm of each (3*num_betas) vector gives you the standard deviation of the component.

**Comment by ZHANG-SHI-CHANG** [comment]
> The shape and expression basis are multiplied by the standard deviation. This allows using a l2 norm as shape or expression prior (which is then equivalent to using Mahalanobis distance on the unit-length components). Varying a shape or oxpression component between +-x corresponds then to a variation of +-x standard deviations.
> 
> If you reshape the shapedirs tensor from (num_verts x 3 x num_betas) to (3_num_verts x num_betas), the norm of each (3_num_betas) vector gives you the standard deviation of the component.

i set variance in [-1, 1] is suitable, beyond this range will generate badcase.
And i use flame model in eos(https://github.com/patrikhuber/eos), the result is not good, can you give some advice about optimizes?
![image](https://user-images.githubusercontent.com/30692249/64236686-84342a80-cf2d-11e9-9672-77f3493c9a9d.png)
![image](https://user-images.githubusercontent.com/30692249/64236734-9c0bae80-cf2d-11e9-9c5b-747e4e2b10f5.png)

**Comment by TimoBolkart** [comment]
So there I guess you fit to 2D keypoints, is that correct? Can you visualize the target 2D keypoints and the keypoints from the model (i.e. visualize the loss)? 

Also, by default, eos does not support FLAME due to the non-linearity caused by the pose articulation. How did you integrate FLAME into this framework?

**Comment by ZHANG-SHI-CHANG** [comment]
> So there I guess you fit to 2D keypoints, is that correct? Can you visualize the target 2D keypoints and the keypoints from the model (i.e. visualize the loss)?
> 
> Also, by default, eos does not support FLAME due to the non-linearity caused by the pose articulation. How did you integrate FLAME into this framework?

first, i parse mean face, shape, expression from your flame model
second, i register 68 lmks by nicp from bfm2009 to flame, like follow
![image](https://user-images.githubusercontent.com/30692249/64239909-a7fa6f00-cf33-11e9-8819-f4c34969236d.png)
then i can use flame to fitting like use bfm, but result is not good, i have no idea about it now.

**Comment by TimoBolkart** [comment]
Just to clarify, you just copy mean template, shape and expression basis and then use it same as you use BFM? The problem is that FLAME (in contrast to BFM or other models) additionally hast parameters for pose (i.e. for head rotation around the neck and jaw rotation to open the mouth). Hence, only considering the shape and expression vectors will be not sufficient as one has to also consider the linear blendskinning for the pose articulation. A proper integration of FLAME into eos could be of interest for more people, maybe Patrik Huber as the author of eos can provide some hints how to properly integrate FLAME including the pose transformations

**Comment by TimoBolkart** [comment]
Can you also please show the BFM fitting for the example above. It looks to me like not even the global pose is properly fit

**Comment by ZHANG-SHI-CHANG** [comment]
> Can you also please show the BFM fitting for the example above. It looks to me like not even the global pose is properly fit

thx~ for your reply, follow is the bfm2017 only face result fitting by eos
![image](https://user-images.githubusercontent.com/30692249/64244069-fe1ee080-cf3a-11e9-8480-6d801787c1ed.png)
may be i can add pose blendshape as expression in eos, i will try it.

**Comment by TimoBolkart** [comment]
Thanks, as I thought before, neither the global transformation nor the shape are properly fit for FLAME. For these I don't know why. The pose is an additional set of parameters and the pose blendshapes are correctives to improve the part-based rotations and they non-lineary depend on the pose. Without Integrating the whole linear blendskinning, I don't see how one can use FLAME within this framework. Just adding the pose blendahapes as expressions will not work

**Comment by ZHANG-SHI-CHANG** [comment]
> Thanks, as I thought before, neither the global transformation nor the shape are properly fit for FLAME. For these I don't know why. The pose is an additional set of parameters and the pose blendshapes are correctives to improve the part-based rotations and they non-lineary depend on the pose. Without Integrating the whole linear blendskinning, I don't see how one can use FLAME within this framework. Just adding the pose blendahapes as expressions will not work

got it, thx~ very much!
