### ISSUE TITLE
Jaw articulation parameters

### ISSUE THREAD

**Issue by prathebaselva** [TimoBolkart/TF_FLAME#73]
Does Pose[3:6] control the jaw articulation? Also what is the range for the articulation?

**Comment by TimoBolkart** [comment]
FLAME's pose is defined as [global rotation, head rotation, jaw rotation, left eyeball rotation, right eyeball rotation]. In some of our code samples like e.g., the same_FLAME.py we separate global rotation from the rest of the pose for simplicity. So yes, in such an example, pose[3:6] represent the rotation of the jaw around its joint in axis-angle representation. So, the normalized vector of the 3D jaw pose vector determines the rotation axis, while the norm of the vector is the magnitude / angle of the rotation. Does this answer your question?

**Comment by prathebaselva** [comment]
I get it. Thank you. So if i want to make an articulated jaw, i feed in a normalized unit vector. But for the magnitude, how much should be the range? Any limit?

**Comment by TimoBolkart** [comment]
Sampling a wide variety of poses for the axis angle representation is not trivial, one easily ends up with unrealistic jaw poses. What exactly do you intend to to?

**Comment by prathebaselva** [comment]
Exactly what I want to try. Given a neutral face I want to visualize different samples of jaw articulation.  And I got unrealistic jaw positions.  Is there any solution to this problem?  Any regularizers for max axis rotation?

**Comment by TimoBolkart** [comment]
There are different possibilities, (a) you select angles in Euler angle representation, considering only yaw and pitch rotations, and convert them to axis-angle representation prior to passing them to FLAME, or (b) you sample only easy jaw poses (e.g., jaw pose [angle, 0, 0] with positive angles to open the mouth, or  [0, angle, 0] to move the jaw left right). Max axis rotations for axis-angle rotations is tricky, but for Euler angles you can certainly do it, you would just need to convert it to FLAME's axis-angle rotation then.

**Comment by prathebaselva** [comment]
will try that. thank you
